language: java
jdk:
  - oraclejdk7

env:
  - TERM=dumb

install:
  - ./gradlew -Pbnd_repourl=https://bndtools.ci.cloudbees.com/job/bnd.next/lastSuccessfulBuild/artifact/dist/bundles --version

script:
  - ./gradlew -Pbnd_repourl=https://bndtools.ci.cloudbees.com/job/bnd.next/lastSuccessfulBuild/artifact/dist/bundles --continue
