language: java
jdk:
  - oraclejdk7

env:
  - TERM=dumb

install:
  - ./gradlew --version
  - mvn --version

script:
  - ./gradlew --continue
  - mvn -f bnd-maven-plugin-parent/bnd-maven-plugin-dependencies -Dmaven.repo.local=bnd-maven-plugin-parent/target/m2 --batch-mode --quiet initialize
  - mvn -f bnd-maven-plugin-parent -Dmaven.repo.local=bnd-maven-plugin-parent/target/m2 --batch-mode --quiet install
