name: 'Rebuild'

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'
  pull_request:
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '17'
    name: Build JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      dist-bundles: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build
      id: build
      run: |
        ./.github/scripts/rebuild-build.sh
    - name: Upload dist/bundles
      uses: actions/upload-artifact@v3
      with:
        name: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
        if-no-files-found: error
        path: dist/bundles/

  rebuild:
    needs: build
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '8'
        - '18'
        runner:
        - 'xvfb-run --auto-servernum {0}'
    name: Rebuild JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Download dist/bundles
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build.outputs.dist-bundles }}
        path: dist/bundles
    - name: Rebuild
      id: build
      run: |
        ${{ format(matrix.runner, './.github/scripts/rebuild-test.sh') }}
    - name: Upload Test Reports
      if: ${{ always() && ((steps.build.outcome == 'success') || (steps.build.outcome == 'failure')) }}
      uses: actions/upload-artifact@v3
      with:
        name: Rebuild_JDK${{ matrix.java }}_${{ matrix.os }}-test-reports
        path: |
          */generated/test-reports/*/TEST-*.xml
          maven/*/target/surefire-reports/TEST-*.xml
          gradle-plugins/*/build/test-results/*/TEST-*.xml
