name: 'Rebuild'


on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'
  pull_request:
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - '.github/**/*rebuild*'

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3
    -Daether.connector.http.retryHandler.count=5
    -Daether.connector.http.reuseConnections=false
    -Daether.connector.http.connectionMaxTtl=25
    -Daether.connector.connectTimeout=120000
  BNDTOOLS_CORE_TEST_NOJUNITOSGI: true # This test is very flaky on CI

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '17'
    name: Build JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      dist-bundles: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        distribution: 'temurin'
        java-version: |
          8
          ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a
    - name: Build
      id: build
      run: |
        ./.github/scripts/rebuild-build.sh
    - name: Upload dist/bundles
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      with:
        name: Dist_Bundles_JDK${{ matrix.java }}_${{ matrix.os }}
        if-no-files-found: error
        path: dist/bundles/

  rebuild:
    needs: build
    strategy:
      fail-fast: ${{ (github.repository != 'bndtools/bnd') || ((github.ref != 'refs/heads/master') && (github.ref != 'refs/heads/next')) || (github.event_name == 'pull_request') }}
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '17'
        - '21'
        - '24'
        #- '25-ea'
        runner:
        - '{0}' # 'xvfb-run --auto-servernum {0}'
    name: Rebuild JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: Set up Java 8 + ${{ matrix.java }}
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        distribution: 'temurin'
        java-version: |
          8
          ${{ matrix.java }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a
    - name: Download dist/bundles
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
      with:
        name: ${{ needs.build.outputs.dist-bundles }}
        path: dist/bundles
    - name: Rebuild
      id: build
      run: |
        ${{ format(matrix.runner, './.github/scripts/rebuild-test.sh') }}
    - name: Upload Test Reports
      if: ${{ always() && ((steps.build.outcome == 'success') || (steps.build.outcome == 'failure')) }}
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      with:
        name: Rebuild_JDK${{ matrix.java }}_${{ matrix.os }}-test-reports
        path: |
          */generated/test-reports/*/TEST-*.xml
          maven/*/target/surefire-reports/TEST-*.xml
          gradle-plugins/*/build/test-results/*/TEST-*.xml
